# Generated by Django 4.0.2 on 2022-04-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutriapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateField(null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
        migrations.AddField(
            model_name='sales',
            name='date',
            field=models.DateField(null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
    ]
